In [12]:
# prompt: mount gdrive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [14]:
import pandas as pd

def load_csvs(file_paths):
    dataframes = []
    for path in file_paths:
        try:
            df = pd.read_csv(path)
            dataframes.append(df)
            print(f"Loaded {path} successfully.")
        except FileNotFoundError:
            print(f"File {path} not found.")
        except Exception as e:
            print(f"An error occurred while loading {path}: {e}")
    return dataframes

# if __name__ == "__main__":
#     # List of file paths
#     file_paths = [r"C:\Users\paude\Documents\00. Backup 2023\EXTERIOR\MASTER\MA IAAC\03. Cursada\01. Modulo 03\S01 DE\Class Project\DE_Team\Scraped_csvs\data_cost.csv",
#                   r"C:\Users\paude\Documents\00. Backup 2023\EXTERIOR\MASTER\MA IAAC\03. Cursada\01. Modulo 03\S01 DE\Class Project\DE_Team\Scraped_csvs\data_prop_price.csv",
#                 r"C:\Users\paude\Documents\00. Backup 2023\EXTERIOR\MASTER\MA IAAC\03. Cursada\01. Modulo 03\S01 DE\Class Project\DE_Team\Scraped_csvs\data_qual.csv"
#                 ]


if __name__ == "__main__":
    # List of file paths
    file_paths = ["/content/drive/MyDrive/Colab Notebooks/DE/Project/Scraped_csvs/data_cost.csv",
                  "/content/drive/MyDrive/Colab Notebooks/DE/Project/Scraped_csvs/data_prop_price.csv",
                "/content/drive/MyDrive/Colab Notebooks/DE/Project/Scraped_csvs/data_qual.csv"
                ]


    # Load CSV files into dataframes
    dfs = load_csvs(file_paths)

Loaded /content/drive/MyDrive/Colab Notebooks/DE/Project/Scraped_csvs/data_cost.csv successfully.
Loaded /content/drive/MyDrive/Colab Notebooks/DE/Project/Scraped_csvs/data_prop_price.csv successfully.
Loaded /content/drive/MyDrive/Colab Notebooks/DE/Project/Scraped_csvs/data_qual.csv successfully.

In [16]:
dfs[0]

,Rank,City,Cost of Living Index,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index
0,1,"Hamilton, Bermuda",137.4,94.7,117.2,147.7,131.3,82.3
1,2,"Basel, Switzerland",120.2,46.6,85.3,135.7,106.7,133.5
2,3,"Zurich, Switzerland",118.3,64.4,92.7,121.0,109.0,132.7
3,4,"Lausanne, Switzerland",117.7,46.4,83.9,123.3,106.2,106.7
4,5,"Bern, Switzerland",110.5,42.3,78.2,108.3,96.5,130.7
...,...,...,...,...,...,...,...,...
365,366,"Kochi, India",20.6,6.6,14.0,23.1,10.7,60.7
366,367,"Coimbatore, India",20.4,4.0,12.6,23.8,11.0,42.5
367,368,"Islamabad, Pakistan",20.3,4.7,12.9,18.1,14.1,24.7
368,369,"Lahore, Pakistan",19.7,3.3,11.9,16.5,15.1,26.3
369,370,"Karachi, Pakistan",19.3,3.0,11.6,17.4,12.2,23.8

In [17]:
dfs[1]

,Rank,City,Price To Income Ratio,Gross Rental Yield City Centre,Gross Rental Yield Outside of Centre,Price To Rent Ratio City Centre,Price To Rent Ratio Outside Of City Centre,Mortgage As A Percentage Of Income,Affordability Index
0,1,"Addis Ababa, Ethiopia",51.6,6.6,4.8,15.2,20.7,861.5,0.1
1,2,"Douala, Cameroon",48.3,10.3,13.0,9.7,7.7,948.9,0.1
2,3,"Shanghai, China",43.5,1.6,1.5,62.6,65.8,337.0,0.3
3,4,"Colombo, Sri Lanka",39.1,4.2,2.1,23.7,47.3,788.5,0.1
4,5,"Tehran, Iran",39.1,4.4,5.0,22.5,20.1,933.2,0.1
...,...,...,...,...,...,...,...,...,...
261,262,"Saint Louis, MO, United States",2.1,13.0,13.0,7.7,7.7,19.0,5.3
262,263,"Memphis, TN, United States",1.8,15.9,15.6,6.3,6.4,16.6,6.0
263,264,"Milwaukee, WI, United States",1.8,19.7,16.4,5.1,6.1,16.4,6.1
264,265,"Indianapolis, IN, United States",1.5,19.4,16.6,5.2,6.0,13.7,7.3
265,266,"Detroit, MI, United States",1.2,32.9,21.8,3.0,4.6,11.0,9.1

In [18]:
dfs[2]

,Rank,City,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index
0,1,"The Hague (Den Haag), Netherlands",224.1,138.9,79.9,80.6,58.1,5.7,21.3,17.6,90.6
1,2,"Luxembourg, Luxembourg",221.3,171.5,71.1,78.2,60.9,9.2,26.6,19.6,82.6
2,3,"Eindhoven, Netherlands",214.3,133.3,77.8,78.3,61.2,6.0,24.9,19.6,85.4
3,4,"Rotterdam, Netherlands",214.1,140.6,71.7,80.6,59.2,5.3,23.4,24.7,87.9
4,5,"Valencia, Spain",202.5,98.7,72.8,80.6,46.3,5.2,22.8,23.4,93.8
...,...,...,...,...,...,...,...,...,...,...,...
194,195,"Caracas, Venezuela",64.4,11.7,18.1,38.1,41.5,27.7,33.7,73.9,99.9
195,196,"Dhaka, Bangladesh",61.1,32.1,37.4,40.2,24.8,14.3,61.4,94.2,71.3
196,197,"Manila, Philippines",53.7,33.6,35.3,62.5,36.0,33.4,51.7,89.8,61.2
197,198,"Tehran, Iran",53.3,20.6,43.2,53.2,28.4,39.1,51.8,80.4,71.0
198,199,"Lagos, Nigeria",44.4,12.2,31.7,47.5,34.6,18.4,68.8,89.0,60.8

In [19]:
merged_df = pd.merge(dfs[0], dfs[1], on='City', how='outer')
merged_df = pd.merge(merged_df, dfs[2], on='City', how='outer')

In [20]:
merged_df.head()
# print(merged_df)
# merged_df.shape

,Rank_x,City,Cost of Living Index_x,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,Rank_y,Price To Income Ratio,...,Rank,Quality of Life Index,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index
0,1.0,"Hamilton, Bermuda",137.4,94.7,117.2,147.7,131.3,82.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,"Basel, Switzerland",120.2,46.6,85.3,135.7,106.7,133.5,111.0,12.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,"Zurich, Switzerland",118.3,64.4,92.7,121.0,109.0,132.7,84.0,14.0,...,6.0,201.2,165.7,77.3,69.9,100.3,14.0,38.9,23.0,81.5
3,4.0,"Lausanne, Switzerland",117.7,46.4,83.9,123.3,106.2,106.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,"Bern, Switzerland",110.5,42.3,78.2,108.3,96.5,130.7,130.0,11.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
merged_df.shape

(394, 26)

# Replacing NaNs

In [22]:
# prompt: Rename "City" to "City, Country_0", then create a new column in merged_df from the last string after the comma or (), then create a new column called City from the first string before the coma or () in City, Country

# Rename "City" to "City, Country_0"
merged_df.rename(columns={'City': 'City, Country_0'}, inplace=True)

# Create a new column from the last string after the comma or ()
merged_df['Country'] = merged_df['City, Country_0'].str.split(',').str[-1].str.split('(').str[0]

# Create a new column called City from the first string before the coma or ()
merged_df['City'] = merged_df['City, Country_0'].str.split(',').str[0].str.split('(').str[0]

# Print the first five rows of the merged_df DataFrame
merged_df.head()

,Rank_x,"City, Country_0",Cost of Living Index_x,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,Rank_y,Price To Income Ratio,...,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,City
0,1.0,"Hamilton, Bermuda",137.4,94.7,117.2,147.7,131.3,82.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bermuda,Hamilton
1,2.0,"Basel, Switzerland",120.2,46.6,85.3,135.7,106.7,133.5,111.0,12.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland,Basel
2,3.0,"Zurich, Switzerland",118.3,64.4,92.7,121.0,109.0,132.7,84.0,14.0,...,165.7,77.3,69.9,100.3,14.0,38.9,23.0,81.5,Switzerland,Zurich
3,4.0,"Lausanne, Switzerland",117.7,46.4,83.9,123.3,106.2,106.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland,Lausanne
4,5.0,"Bern, Switzerland",110.5,42.3,78.2,108.3,96.5,130.7,130.0,11.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland,Bern

In [23]:
# prompt: in merged_df concatenate City and Country as 'City, Country' and add it to a new column named 'City, Country'

merged_df['City, Country'] = merged_df['City'] + ',' + merged_df['Country']

merged_df.head()

,Rank_x,"City, Country_0",Cost of Living Index_x,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,Rank_y,Price To Income Ratio,...,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,City,"City, Country"
0,1.0,"Hamilton, Bermuda",137.4,94.7,117.2,147.7,131.3,82.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bermuda,Hamilton,"Hamilton, Bermuda"
1,2.0,"Basel, Switzerland",120.2,46.6,85.3,135.7,106.7,133.5,111.0,12.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland,Basel,"Basel, Switzerland"
2,3.0,"Zurich, Switzerland",118.3,64.4,92.7,121.0,109.0,132.7,84.0,14.0,...,77.3,69.9,100.3,14.0,38.9,23.0,81.5,Switzerland,Zurich,"Zurich, Switzerland"
3,4.0,"Lausanne, Switzerland",117.7,46.4,83.9,123.3,106.2,106.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland,Lausanne,"Lausanne, Switzerland"
4,5.0,"Bern, Switzerland",110.5,42.3,78.2,108.3,96.5,130.7,130.0,11.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Switzerland,Bern,"Bern, Switzerland"

## Rounding the numbers

In [24]:
# prompt: for numeric data only, replace the NaN's with the average values of the same columns who share a similar Country, change the data frame name to merged_filled1_ df, for numeric data only round the floats to one decimal number

# Create a copy of the dataframe
merged_filled1_df = merged_df.copy()

# Select numeric columns
numeric_columns = merged_filled1_df.select_dtypes(include=['float64', 'int64']).columns

# Group the dataframe by country and calculate the mean for each numeric column
country_means = merged_filled1_df.groupby('Country')[numeric_columns].mean().round(1)

# Replace NaN values in the numeric columns with the corresponding country mean
for col in numeric_columns:
    for country in country_means.index:
        merged_filled1_df.loc[(merged_filled1_df['Country'] == country) & (merged_filled1_df[col].isna()), col] = country_means.loc[country, col]

# Display the first few rows of the dataframe
merged_filled1_df.head()

,Rank_x,"City, Country_0",Cost of Living Index_x,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,Rank_y,Price To Income Ratio,...,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,City,"City, Country"
0,1.0,"Hamilton, Bermuda",137.4,94.7,117.2,147.7,131.3,82.3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bermuda,Hamilton,"Hamilton, Bermuda"
1,2.0,"Basel, Switzerland",120.2,46.6,85.3,135.7,106.7,133.5,111.0,12.4,...,73.4,70.8,99.8,13.4,35.0,24.0,82.0,Switzerland,Basel,"Basel, Switzerland"
2,3.0,"Zurich, Switzerland",118.3,64.4,92.7,121.0,109.0,132.7,84.0,14.0,...,77.3,69.9,100.3,14.0,38.9,23.0,81.5,Switzerland,Zurich,"Zurich, Switzerland"
3,4.0,"Lausanne, Switzerland",117.7,46.4,83.9,123.3,106.2,106.7,108.2,12.6,...,73.4,70.8,99.8,13.4,35.0,24.0,82.0,Switzerland,Lausanne,"Lausanne, Switzerland"
4,5.0,"Bern, Switzerland",110.5,42.3,78.2,108.3,96.5,130.7,130.0,11.4,...,73.4,70.8,99.8,13.4,35.0,24.0,82.0,Switzerland,Bern,"Bern, Switzerland"

In [25]:
# prompt: check merged_filled1_df for NaN's

merged_filled1_df.isnull().sum()

Rank_x                                         3
City, Country_0                                0
Cost of Living Index_x                         3
Rent Index                                     3
Cost of Living Plus Rent Index                 3
Groceries Index                                3
Restaurant Price Index                         3
Local Purchasing Power Index                   3
Rank_y                                        11
Price To Income Ratio                         11
Gross Rental Yield City Centre                11
Gross Rental Yield Outside of Centre          11
Price To Rent Ratio City Centre               11
Price To Rent Ratio Outside Of City Centre    11
Mortgage As A Percentage Of Income            11
Affordability Index                           11
Rank                                          29
Quality of Life Index                         29
Purchasing Power Index                        29
Safety Index                                  29
Health Care Index                             29
Cost of Living Index_y                        29
Property Price to Income Ratio                29
Traffic Commute Time Index                    29
Pollution Index                               29
Climate Index                                 29
Country                                        0
City                                           0
City, Country                                  0
dtype: int64

In [26]:
# prompt: for numeric data only, replace the NaN's with the average values of the same columns, change the data frame name to merged_filled2_ df

# Create a copy of the dataframe
merged_filled2_df = merged_filled1_df.copy()

# Select numeric columns
numeric_columns = merged_filled2_df.select_dtypes(include=['float64', 'int64']).columns

# Calculate the average values for each numeric column
column_means = merged_filled2_df[numeric_columns].mean()

# Replace NaN values with the average values
merged_filled2_df[numeric_columns] = merged_filled2_df[numeric_columns].fillna(column_means)

# Display the first few rows of the dataframe
merged_filled2_df.head()

,Rank_x,"City, Country_0",Cost of Living Index_x,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,Rank_y,Price To Income Ratio,...,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,City,"City, Country"
0,1.0,"Hamilton, Bermuda",137.4,94.7,117.2,147.7,131.3,82.3,137.702611,12.135248,...,57.853425,67.508493,53.478356,12.152603,36.078356,49.834521,77.721096,Bermuda,Hamilton,"Hamilton, Bermuda"
1,2.0,"Basel, Switzerland",120.2,46.6,85.3,135.7,106.7,133.5,111.000000,12.400000,...,73.400000,70.800000,99.800000,13.400000,35.000000,24.000000,82.000000,Switzerland,Basel,"Basel, Switzerland"
2,3.0,"Zurich, Switzerland",118.3,64.4,92.7,121.0,109.0,132.7,84.000000,14.000000,...,77.300000,69.900000,100.300000,14.000000,38.900000,23.000000,81.500000,Switzerland,Zurich,"Zurich, Switzerland"
3,4.0,"Lausanne, Switzerland",117.7,46.4,83.9,123.3,106.2,106.7,108.200000,12.600000,...,73.400000,70.800000,99.800000,13.400000,35.000000,24.000000,82.000000,Switzerland,Lausanne,"Lausanne, Switzerland"
4,5.0,"Bern, Switzerland",110.5,42.3,78.2,108.3,96.5,130.7,130.000000,11.400000,...,73.400000,70.800000,99.800000,13.400000,35.000000,24.000000,82.000000,Switzerland,Bern,"Bern, Switzerland"

In [27]:
merged_filled2_df.isnull().sum()

Rank_x                                        0
City, Country_0                               0
Cost of Living Index_x                        0
Rent Index                                    0
Cost of Living Plus Rent Index                0
Groceries Index                               0
Restaurant Price Index                        0
Local Purchasing Power Index                  0
Rank_y                                        0
Price To Income Ratio                         0
Gross Rental Yield City Centre                0
Gross Rental Yield Outside of Centre          0
Price To Rent Ratio City Centre               0
Price To Rent Ratio Outside Of City Centre    0
Mortgage As A Percentage Of Income            0
Affordability Index                           0
Rank                                          0
Quality of Life Index                         0
Purchasing Power Index                        0
Safety Index                                  0
Health Care Index                             0
Cost of Living Index_y                        0
Property Price to Income Ratio                0
Traffic Commute Time Index                    0
Pollution Index                               0
Climate Index                                 0
Country                                       0
City                                          0
City, Country                                 0
dtype: int64

# Editing rows and columns to match the new dataset

In [28]:
# prompt: for numeric data only, round the data in all the merged_filled2_df to one decimal figure, then round the data in Rank_x and Rank_y to integers

import numpy as np

# Round numeric data to one decimal figure
for col in merged_filled2_df.select_dtypes(include=['float64', 'int64']):
    merged_filled2_df[col] = np.round(merged_filled2_df[col], 1)

# Round Rank_x and Rank_y to integers
merged_filled2_df['Rank_x'] = merged_filled2_df['Rank_x'].astype(int)
merged_filled2_df['Rank_y'] = merged_filled2_df['Rank_y'].astype(int)

# Display the first few rows of the dataframe
merged_filled2_df.head()

,Rank_x,"City, Country_0",Cost of Living Index_x,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,Rank_y,Price To Income Ratio,...,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,City,"City, Country"
0,1,"Hamilton, Bermuda",137.4,94.7,117.2,147.7,131.3,82.3,137,12.1,...,57.9,67.5,53.5,12.2,36.1,49.8,77.7,Bermuda,Hamilton,"Hamilton, Bermuda"
1,2,"Basel, Switzerland",120.2,46.6,85.3,135.7,106.7,133.5,111,12.4,...,73.4,70.8,99.8,13.4,35.0,24.0,82.0,Switzerland,Basel,"Basel, Switzerland"
2,3,"Zurich, Switzerland",118.3,64.4,92.7,121.0,109.0,132.7,84,14.0,...,77.3,69.9,100.3,14.0,38.9,23.0,81.5,Switzerland,Zurich,"Zurich, Switzerland"
3,4,"Lausanne, Switzerland",117.7,46.4,83.9,123.3,106.2,106.7,108,12.6,...,73.4,70.8,99.8,13.4,35.0,24.0,82.0,Switzerland,Lausanne,"Lausanne, Switzerland"
4,5,"Bern, Switzerland",110.5,42.3,78.2,108.3,96.5,130.7,130,11.4,...,73.4,70.8,99.8,13.4,35.0,24.0,82.0,Switzerland,Bern,"Bern, Switzerland"

In [30]:
# sort data in merged_filled3_df by 'City, Country'

merged_filled3_df = merged_filled2_df.sort_values(by='City, Country', inplace=False)


merged_filled3_df.head()

,Rank_x,"City, Country_0",Cost of Living Index_x,Rent Index,Cost of Living Plus Rent Index,Groceries Index,Restaurant Price Index,Local Purchasing Power Index,Rank_y,Price To Income Ratio,...,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country,City,"City, Country"
155,156,"Aachen, Germany",61.3,20.5,42.0,56.7,52.1,110.7,156,10.0,...,61.7,74.8,63.6,9.4,30.4,33.3,82.1,Germany,Aachen,"Aachen, Germany"
35,36,"Aarhus, Denmark",77.0,29.8,54.6,70.1,81.7,103.9,199,7.7,...,74.4,77.0,74.7,8.4,27.7,21.1,83.7,Denmark,Aarhus,"Aarhus, Denmark"
122,123,"Aberdeen, United Kingdom",65.1,24.4,45.8,56.1,61.3,113.8,135,11.2,...,50.0,74.8,65.8,8.8,35.8,44.7,86.3,United Kingdom,Aberdeen,"Aberdeen, United Kingdom"
163,164,"Abu Dhabi, United Arab Emirates",59.3,46.8,53.4,43.1,63.6,105.9,213,6.5,...,88.1,71.0,54.5,6.5,31.7,46.6,43.9,United Arab Emirates,Abu Dhabi,"Abu Dhabi, United Arab Emirates"
344,345,"Accra, Ghana",27.4,10.6,19.4,29.0,23.2,14.3,137,12.1,...,57.9,67.5,53.5,12.2,36.1,49.8,77.7,Ghana,Accra,"Accra, Ghana"

In [31]:
# Save merged_filled2_df as a CSV file

merged_filled3_df.to_csv("/content/drive/MyDrive/Colab Notebooks/DE/Project/Modified_csvs/Merged_data_filled.csv", index=False)

# merged_filled3_df.to_csv(r"C:\Users\paude\Documents\00. Backup 2023\EXTERIOR\MASTER\MA IAAC\03. Cursada\01. Modulo 03\S01 DE\Class Project\DE_Team\Scraped_csvs\data_cost.csv", index=False)

#New Cities Dataframe

In [32]:
# read csv file "/content/drive/MyDrive/Colab Notebooks/DE/Project/Raw_csvs/worldcities.csv" from Gdrive

all_cities_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DE/Project/Raw_csvs/worldcities.csv")

all_cities_df.head(10)

,City,Country,Lat,Lng,iso2,iso3,Population,ID
0,Tokyo,Japan,35.6897,139.6922,JP,JPN,37732000.0,1392685764
1,Jakarta,Indonesia,-6.1750,106.8275,ID,IDN,33756000.0,1360771077
2,Delhi,India,28.6100,77.2300,IN,IND,32226000.0,1356872604
3,Guangzhou,China,23.1300,113.2600,CN,CHN,26940000.0,1156237133
4,Mumbai,India,19.0761,72.8775,IN,IND,24973000.0,1356226629
5,Manila,Philippines,14.5958,120.9772,PH,PHL,24922000.0,1608618140
6,Shanghai,China,31.2286,121.4747,CN,CHN,24073000.0,1156073548
7,Sao Paulo,Brazil,-23.5500,-46.6333,BR,BRA,23086000.0,1076532519
8,Seoul,"Korea, South",37.5600,126.9900,KR,KOR,23016000.0,1410836482
9,Mexico City,Mexico,19.4333,-99.1333,MX,MEX,21804000.0,1484247881

In [33]:
# prompt: in all_cities_df, concatenate City and Country as: 'City, Country' in a new column called 'City, Country'

all_cities_df['City, Country'] = all_cities_df['City'] + ', ' + all_cities_df['Country']

# prompt: sort all_cities_df by 'Population'

all_cities_df.sort_values(by='Population', inplace=True, ascending=False)

all_cities_df.head()

,City,Country,Lat,Lng,iso2,iso3,Population,ID,"City, Country"
0,Tokyo,Japan,35.6897,139.6922,JP,JPN,37732000.0,1392685764,"Tokyo, Japan"
1,Jakarta,Indonesia,-6.1750,106.8275,ID,IDN,33756000.0,1360771077,"Jakarta, Indonesia"
2,Delhi,India,28.6100,77.2300,IN,IND,32226000.0,1356872604,"Delhi, India"
3,Guangzhou,China,23.1300,113.2600,CN,CHN,26940000.0,1156237133,"Guangzhou, China"
4,Mumbai,India,19.0761,72.8775,IN,IND,24973000.0,1356226629,"Mumbai, India"

In [34]:
all_cities_df.shape

(47868, 9)

In [35]:
# keep only the first 1000 rows in all_cities_df

# cities_1000_df = all_cities_df.head(1000)

# cities_1000_df.head(50)

In [36]:
# prompt: merge all_cities_df and merged_filled3_df on 'City, Country'

import pandas as pd
merged_cities_df = pd.merge(all_cities_df, merged_filled3_df, on='City, Country', how='outer')

# Display the first few rows of the dataframe
merged_cities_df.head(50)

,City_x,Country_x,Lat,Lng,iso2,iso3,Population,ID,"City, Country",Rank_x,...,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country_y,City_y
0,Tokyo,Japan,35.6897,139.6922,JP,JPN,37732000.0,1.392686e+09,"Tokyo, Japan",169.0,...,111.2,76.0,79.2,53.6,12.9,42.5,42.0,85.3,Japan,Tokyo
1,Jakarta,Indonesia,-6.1750,106.8275,ID,IDN,33756000.0,1.360771e+09,"Jakarta, Indonesia",312.0,...,43.4,47.3,56.9,30.0,15.8,53.1,84.7,63.8,Indonesia,Jakarta
2,Delhi,India,28.6100,77.2300,IN,IND,32226000.0,1.356873e+09,"Delhi, India",354.0,...,118.8,41.0,66.7,23.4,8.8,57.9,90.3,58.9,India,Delhi
3,Guangzhou,China,23.1300,113.2600,CN,CHN,26940000.0,1.156237e+09,"Guangzhou, China",285.0,...,90.2,72.5,66.6,36.4,37.3,45.7,74.7,70.6,China,Guangzhou
4,Mumbai,India,19.0761,72.8775,IN,IND,24973000.0,1.356227e+09,"Mumbai, India",351.0,...,70.2,55.3,65.3,23.8,32.6,55.0,83.5,71.5,India,Mumbai
5,Manila,Philippines,14.5958,120.9772,PH,PHL,24922000.0,1.608618e+09,"Manila, Philippines",262.0,...,33.6,35.3,62.5,36.0,33.4,51.7,89.8,61.2,Philippines,Manila
6,Shanghai,China,31.2286,121.4747,CN,CHN,24073000.0,1.156074e+09,"Shanghai, China",238.0,...,77.0,71.4,64.4,38.0,43.5,47.8,71.5,83.6,China,Shanghai
7,Sao Paulo,Brazil,-23.5500,-46.6333,BR,BRA,23086000.0,1.076533e+09,"Sao Paulo, Brazil",252.0,...,30.8,29.6,59.9,37.5,23.4,50.8,79.0,99.0,Brazil,Sao Paulo
8,Seoul,"Korea, South",37.5600,126.9900,KR,KOR,23016000.0,1.410836e+09,"Seoul, Korea, South",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Mexico City,Mexico,19.4333,-99.1333,MX,MEX,21804000.0,1.484248e+09,"Mexico City, Mexico",206.0,...,39.4,32.2,65.9,46.1,16.8,53.1,81.5,92.4,Mexico,Mexico City
10,Cairo,Egypt,30.0444,31.2358,EG,EGY,20296000.0,1.818254e+09,"Cairo, Egypt",324.0,...,18.0,49.3,45.9,20.4,18.0,49.9,90.8,88.5,Egypt,Cairo
11,New York,United States,40.6943,-73.9249,US,USA,18908608.0,1.840034e+09,"New York, United States",7.0,...,100.0,49.3,62.7,100.0,13.0,43.6,58.3,79.7,United States,New York
12,Dhaka,Bangladesh,23.7639,90.3889,BD,BGD,18627000.0,1.050529e+09,"Dhaka, Bangladesh",341.0,...,32.1,37.4,40.2,24.8,14.3,61.4,94.2,71.3,Bangladesh,Dhaka
13,Beijing,China,39.9067,116.3975,CN,CHN,18522000.0,1.156229e+09,"Beijing, China",267.0,...,103.3,73.6,68.8,34.8,31.1,43.6,77.9,57.6,China,Beijing
14,Kolkata,India,22.5675,88.3700,IN,IND,18502000.0,1.356061e+09,"Kolkata, India",364.0,...,63.6,54.0,59.8,20.6,8.5,59.6,78.4,60.9,India,Kolkata
15,Bangkok,Thailand,13.7525,100.4942,TH,THA,18007000.0,1.764069e+09,"Bangkok, Thailand",235.0,...,39.0,60.2,76.7,39.2,29.2,45.6,77.9,58.4,Thailand,Bangkok
16,Shenzhen,China,22.5415,114.0596,CN,CHN,17619000.0,1.156159e+09,"Shenzhen, China",269.0,...,90.2,72.5,66.6,36.4,37.3,45.7,74.7,70.6,China,Shenzhen
17,Moscow,Russia,55.7558,37.6172,RU,RUS,17332000.0,1.643318e+09,"Moscow, Russia",280.0,...,71.6,64.1,67.1,35.7,18.8,50.4,55.2,55.8,Russia,Moscow
18,Buenos Aires,Argentina,-34.6033,-58.3817,AR,ARG,16710000.0,1.032717e+09,"Buenos Aires, Argentina",344.0,...,32.3,36.6,68.4,30.7,25.0,49.8,51.8,98.3,Argentina,Buenos Aires
19,Lagos,Nigeria,6.4550,3.3841,NG,NGA,16637000.0,1.566594e+09,"Lagos, Nigeria",362.0,...,12.2,31.7,47.5,34.6,18.4,68.8,89.0,60.8,Nigeria,Lagos
20,Istanbul,Turkey,41.0136,28.9550,TR,TUR,16079000.0,1.792756e+09,"Istanbul, Turkey",270.0,...,47.2,52.2,69.9,37.5,15.8,51.4,68.2,93.0,Turkey,Istanbul
21,Karachi,Pakistan,24.8600,67.0100,PK,PAK,15738000.0,1.586129e+09,"Karachi, Pakistan",370.0,...,27.1,43.6,56.5,18.7,12.9,42.5,89.3,71.3,Pakistan,Karachi
22,Bangalore,India,12.9789,77.5917,IN,IND,15386000.0,1.356410e+09,"Bangalore, India",326.0,...,164.0,45.6,64.9,25.3,7.2,53.5,83.1,89.4,India,Bangalore
23,Ho Chi Minh City,Vietnam,10.7756,106.7019,VN,VNM,15136000.0,1.704774e+09,"Ho Chi Minh City, Vietnam",310.0,...,36.0,47.9,61.1,29.9,36.6,31.9,92.5,63.4,Vietnam,Ho Chi Minh City
24,Osaka,Japan,34.6939,135.5022,JP,JPN,15126000.0,1.392420e+09,"Osaka, Japan",207.0,...,111.2,76.0,79.2,53.6,12.9,42.5,42.0,85.3,Japan,Osaka
25,Chengdu,China,30.6600,104.0633,CN,CHN,14645000.0,1.156422e+09,"Chengdu, China",315.0,...,90.2,72.5,66.6,36.4,37.3,45.7,74.7,70.6,China,Chengdu
26,Tehran,Iran,35.6892,51.3889,IR,IRN,14148000.0,1.364305e+09,"Tehran, Iran",323.0,...,20.6,43.2,53.2,28.4,39.1,51.8,80.4,71.0,Iran,Tehran
27,Kinshasa,Congo (Kinshasa),-4.3219,15.3119,CD,COD,12836000.0,1.180000e+09,"Kinshasa, Congo (Kinshasa)",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Rio de Janeiro,Brazil,-22.9111,-43.2056,BR,BRA,12592000.0,1.076888e+09,"Rio de Janeiro, Brazil",258.0,...,23.9,22.6,45.5,36.5,24.7,51.8,67.3,88.2,Brazil,Rio de Janeiro
29,Chennai,India,13.0825,80.2750,IN,IND,12395000.0,1.356375e+09,"Chennai, India",358.0,...,101.9,60.1,69.4,21.3,8.6,46.7,74.7,53.2,India,Chennai
30,Xi'an,China,34.2611,108.9422,CN,CHN,12328000.0,1.156244e+09,"Xi'an, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Lahore,Pakistan,31.5497,74.3436,PK,PAK,12306000.0,1.586801e+09,"Lahore, Pakistan",369.0,...,29.7,63.6,62.3,18.9,13.6,34.7,78.7,67.6,Pakistan,Lahore
32,Chongqing,China,29.5637,106.5504,CN,CHN,12135000.0,1.156937e+09,"Chongqing, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Los Angeles,United States,34.1141,-118.4068,US,USA,11922389.0,1.840020e+09,"Los Angeles, United States",17.0,...,126.0,47.0,61.1,80.2,7.1,57.5,67.4,95.5,United States,Los Angeles
34,Baoding,China,38.8740,115.4640,CN,CHN,11544036.0,1.156257e+09,"Baoding, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,London,United Kingdom,51.5072,-0.1275,GB,GBR,11262000.0,1.826646e+09,"London, United Kingdom",27.0,...,101.2,45.4,70.0,76.9,16.0,44.7,57.9,88.3,United Kingdom,London
36,Paris,France,48.8567,2.3522,FR,FRA,11060000.0,1.250015e+09,"Paris, France",46.0,...,92.7,42.3,77.5,72.7,17.5,41.3,64.8,88.4,France,Paris
37,Linyi,China,35.1038,118.3564,CN,CHN,11018365.0,1.156086e+09,"Linyi, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Dongguan,China,23.0210,113.7520,CN,CHN,10646000.0,1.156478e+09,"Dongguan, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Dongguan,China,39.0140,111.0768,CN,CHN,75135.0,1.156887e+09,"Dongguan, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Hyderabad,India,17.3617,78.4747,IN,IND,10494000.0,1.356872e+09,"Hyderabad, India",355.0,...,112.2,56.7,65.3,22.9,5.4,42.4,76.1,73.5,India,Hyderabad
41,Tianjin,China,39.1336,117.2054,CN,CHN,10368000.0,1.156174e+09,"Tianjin, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Lima,Peru,-12.0600,-77.0375,PE,PER,10320000.0,1.604729e+09,"Lima, Peru",292.0,...,30.5,29.1,58.1,34.0,16.6,50.4,85.3,97.7,Peru,Lima
43,Wuhan,China,30.5934,114.3046,CN,CHN,10251000.0,1.156117e+09,"Wuhan, China",304.0,...,90.2,72.5,66.6,36.4,37.3,45.7,74.7,70.6,China,Wuhan
44,Nanyang,China,32.9987,112.5292,CN,CHN,9713112.0,1.156192e+09,"Nanyang, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Hangzhou,China,30.2670,120.1530,CN,CHN,9523000.0,1.156275e+09,"Hangzhou, China",281.0,...,90.2,72.5,66.6,36.4,37.3,45.7,74.7,70.6,China,Hangzhou
46,Foshan,China,23.0214,113.1216,CN,CHN,9498863.0,1.156738e+09,"Foshan, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Nagoya,Japan,35.1833,136.9000,JP,JPN,9197000.0,1.392407e+09,"Nagoya, Japan",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Tongshan,China,34.2040,117.2840,CN,CHN,9083790.0,1.156242e+09,"Tongshan, China",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Luanda,Angola,-8.8383,13.2344,AO,AGO,9051000.0,1.024950e+09,"Luanda, Angola",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
merged_cities_df.shape

(47902, 37)

In [38]:
# merged_cities_1000_df.to_csv("/content/drive/MyDrive/Colab Notebooks/DE/Project/Raw_csvs/merged_cities_1000.csv", index=False)

merged_cities_df.to_csv("/content/drive/MyDrive/Colab Notebooks/DE/Project/Modified_csvs/merged_cities.csv", index=False)

# Filling the missing data in the merged cities

In [39]:
# prompt: in merged_cities_df, if numeric data, replace the NaN's with the average of numeric values of the same columns who share a similar Country_x, change the data frame name to merged_cities_ filled_df

# Create a copy of the dataframe
merged_cities_filled_df = merged_cities_df.copy()

# Select numeric columns
numeric_columns = merged_cities_filled_df.select_dtypes(include=['float64', 'int64']).columns

# Group the dataframe by Country_x and calculate the mean for each numeric column
country_means = merged_cities_filled_df.groupby('Country_x')[numeric_columns].mean().round(1)

# Replace NaN values in the numeric columns with the corresponding country mean
for col in numeric_columns:
    for country in country_means.index:
        merged_cities_filled_df.loc[(merged_cities_filled_df['Country_x'] == country) & (merged_cities_filled_df[col].isna()), col] = country_means.loc[country, col]

# Display the first few rows of the dataframe
merged_cities_filled_df.head()

,City_x,Country_x,Lat,Lng,iso2,iso3,Population,ID,"City, Country",Rank_x,...,Purchasing Power Index,Safety Index,Health Care Index,Cost of Living Index_y,Property Price to Income Ratio,Traffic Commute Time Index,Pollution Index,Climate Index,Country_y,City_y
0,Tokyo,Japan,35.6897,139.6922,JP,JPN,37732000.0,1.392686e+09,"Tokyo, Japan",169.0,...,111.2,76.0,79.2,53.6,12.9,42.5,42.0,85.3,Japan,Tokyo
1,Jakarta,Indonesia,-6.1750,106.8275,ID,IDN,33756000.0,1.360771e+09,"Jakarta, Indonesia",312.0,...,43.4,47.3,56.9,30.0,15.8,53.1,84.7,63.8,Indonesia,Jakarta
2,Delhi,India,28.6100,77.2300,IN,IND,32226000.0,1.356873e+09,"Delhi, India",354.0,...,118.8,41.0,66.7,23.4,8.8,57.9,90.3,58.9,India,Delhi
3,Guangzhou,China,23.1300,113.2600,CN,CHN,26940000.0,1.156237e+09,"Guangzhou, China",285.0,...,90.2,72.5,66.6,36.4,37.3,45.7,74.7,70.6,China,Guangzhou
4,Mumbai,India,19.0761,72.8775,IN,IND,24973000.0,1.356227e+09,"Mumbai, India",351.0,...,70.2,55.3,65.3,23.8,32.6,55.0,83.5,71.5,India,Mumbai

In [40]:
merged_cities_filled_df.to_csv("/content/drive/MyDrive/Colab Notebooks/DE/Project/Modified_csvs/merged_cities_filled.csv", index=False)

# merged_cities_filled_df.to_csv(r"C:\Users\paude\Documents\00. Backup 2023\EXTERIOR\MASTER\MA IAAC\03. Cursada\01. Modulo 03\S01 DE\Class Project\DE_Team\Modified_csvs\123.csv", index=False)